"use server";
import { createHash, randomUUID } from "node:crypto";
import { redirect } from "next/navigation";
import { revalidatePath } from "next/cache";
import { getOwnerContext } from "@/lib/auth/owner";
import { createSignedUploadTarget, type UploadTarget } from "@/lib/imports/uploadTarget";
import { CELLARTRACKER_MAX_FILE_BYTES, CELLARTRACKER_PARSER_VERSION, CellarTrackerFileError, parseCellarTrackerCsv } from "@/lib/cellar/cellartrackerParser";
const BASE="/cellar/imports/cellartracker";
export async function createCellarTrackerUploadTarget(fileName:string,fileSize:number):Promise<UploadTarget|{error:string}>{ const c=await getOwnerContext(); if(!c)return{error:"Your owner session has expired. Sign in again."}; if(!fileName.toLowerCase().endsWith(".csv")||fileSize<=0||fileSize>CELLARTRACKER_MAX_FILE_BYTES)return{error:"Choose a non-empty CellarTracker CSV under 4 MB."}; const result=await createSignedUploadTarget(c.supabase,c.userId,randomUUID(),"source.csv"); return "error" in result?result:result.target; }
export async function processCellarTrackerUpload(input:{importId:string;objectPath:string;originalFilename:string}):Promise<{error:string}|{redirectTo:string}>{ const c=await getOwnerContext(); if(!c)return{error:"Your owner session has expired. Sign in again."}; if(!input.objectPath.startsWith(`${c.userId}/${input.importId}/`))return{error:"The uploaded file reference is invalid."}; const {data,error}=await c.supabase.storage.from("cellar-imports").download(input.objectPath); if(error||!data)return{error:"The uploaded file could not be read."}; const bytes=new Uint8Array(await data.arrayBuffer()); if(!bytes.length||bytes.length>CELLARTRACKER_MAX_FILE_BYTES)return{error:"The file exceeds the 4 MB import limit."}; let rows; try { rows=parseCellarTrackerCsv(new TextDecoder("windows-1252",{fatal:true}).decode(bytes)); } catch(e) { return{error:e instanceof CellarTrackerFileError?e.message:"The CellarTracker CSV could not be parsed."}; } const checksum=createHash("sha256").update(bytes).digest("hex"); const {data:result,error:stageError}=await c.supabase.rpc("stage_cellartracker_import",{p_import_id:input.importId,p_content_checksum:checksum,p_original_filename:input.originalFilename.slice(0,255),p_byte_size:bytes.length,p_storage_object_path:input.objectPath,p_parser_version:CELLARTRACKER_PARSER_VERSION,p_rows:rows}); if(stageError||!(result as {import_id?:string})?.import_id)return{error:"The parsed import could not be recorded atomically."}; const value=result as {import_id:string;duplicate?:boolean}; if(value.duplicate) await c.supabase.storage.from("cellar-imports").remove([input.objectPath]); revalidatePath("/cellar/imports"); revalidatePath(BASE); return{redirectTo:`${BASE}/${value.import_id}${value.duplicate?"?duplicate=1":""}`}; }
export async function acceptCellarTrackerImport(id:string):Promise<never>{const c=await getOwnerContext();if(!c)redirect("/login");const {error}=await c.supabase.rpc("accept_cellartracker_import",{p_import_id:id});revalidatePath("/cellartracker");revalidatePath("/cellar/imports");revalidatePath(BASE);revalidatePath(`${BASE}/${id}`);redirect(`${BASE}/${id}?${error?"accept_error=1":"accepted=1"}`);}
export async function discardCellarTrackerImportRow(importId:string, sourceRowNumber:number):Promise<never>{const c=await getOwnerContext();if(!c)redirect("/login");const {error}=await c.supabase.rpc("discard_cellartracker_import_row",{p_import_id:importId,p_source_row_number:sourceRowNumber});revalidatePath("/cellar/imports");revalidatePath(BASE);revalidatePath(`${BASE}/${importId}`);redirect(`${BASE}/${importId}?${error?"discard_error=1":"discarded=1"}`);}
export async function repairCellarTrackerImportPrice(importId:string, sourceRowNumber:number, formData:FormData):Promise<never>{const input=String(formData.get("price")??"").trim();const value=/^\d+(?:\.\d{1,2})?$/.test(input)?Math.round(Number(input)*100):null;if(value===null)redirect(`${BASE}/${importId}?repair_error=1`);const c=await getOwnerContext();if(!c)redirect("/login");const {error}=await c.supabase.rpc("repair_cellartracker_import_price",{p_import_id:importId,p_source_row_number:sourceRowNumber,p_price_p:value});revalidatePath("/cellar/imports");revalidatePath(BASE);revalidatePath(`${BASE}/${importId}`);redirect(`${BASE}/${importId}?${error?"repair_error=1":"repaired=1"}`);}
export async function repairCellarTrackerImportRow(importId:string, sourceRowNumber:number, formData:FormData):Promise<never>{let raw:Record<string,string>;try{raw=JSON.parse(String(formData.get("raw_row")??""));}catch{redirect(`${BASE}/${importId}?repair_error=1`);}for(const field of ["Wine","Vintage","Size","Currency","Price","TotalQuantity","Quantity","Pending"])raw[field]=String(formData.get(field)??"").trim();const c=await getOwnerContext();if(!c)redirect("/login");const {error}=await c.supabase.rpc("repair_cellartracker_import_row",{p_import_id:importId,p_source_row_number:sourceRowNumber,p_raw_row:raw});revalidatePath("/cellar/imports");revalidatePath(BASE);revalidatePath(`${BASE}/${importId}`);redirect(`${BASE}/${importId}?${error?"repair_error=1":"repaired=1"}`);}
export async function deleteCellarTrackerImport(importId:string):Promise<never>{const c=await getOwnerContext();if(!c)redirect("/login");const {data,error:readError}=await c.supabase.from("cellar_imports").select("storage_object_path").eq("id",importId).eq("source_type","cellartracker_inventory").maybeSingle();if(readError||!data?.storage_object_path)redirect(`${BASE}/${importId}?delete_error=1`);const {error:storageError}=await c.supabase.storage.from("cellar-imports").remove([data.storage_object_path]);if(storageError)redirect(`${BASE}/${importId}?delete_error=1`);const {error}=await c.supabase.rpc("delete_cellartracker_import",{p_import_id:importId});revalidatePath("/cellar/imports");revalidatePath(BASE);revalidatePath("/cellartracker");redirect(error?`${BASE}/${importId}?delete_error=1`:`${BASE}?deleted=1`);}
