import { createClient } from "@supabase/supabase-js";
import type { Database } from "@/lib/database.types";

const url = process.env.NEXT_PUBLIC_SUPABASE_URL!;
const anonKey = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!;

// The password recovery link generated by forgot-password/actions.ts uses
// implicit flow (its cookie-less server-action client can't persist a PKCE
// code verifier), delivering session tokens in the redirect URL hash. The
// shared @supabase/ssr browser client can't consume that: createBrowserClient
// hard-codes flowType to "pkce" and ignores any override, so it never reads
// the hash. This client is scoped to the update-password page only, reads
// the hash-based session, and is never persisted beyond that page load.
export const recoverySupabase = createClient<Database>(url, anonKey, {
  auth: {
    flowType: "implicit",
    detectSessionInUrl: true,
    persistSession: false,
    autoRefreshToken: false,
  },
});
